import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from "next/router";
import {useEffect, useState} from 'react'
import { getProviders, getSession, useSession } from "next-auth/react";
import Login from '../components/Login';

export default function Home({providers}) {

  const router = useRouter();
  const {data: session} = useSession()
  const [Loading, SetLoading] = useState(true)

  console.log(session)
  // useEffect(() => { 
  //   setTimeout(() => {
  //     if(!session.data){
  //       router.push('/signin')
  //     } else {
  //       SetLoading(false)
  //     } 
  //   }, 5000);
  // }, [])

  // if(Loading) return "Loading"

  // if(!session) return <Login/>

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          HOME
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


// export async function getServerSideProps(context) {
//   const session = await getSession(context)

//   if (!session) {
//     return {
//       redirect: {
//         destination: '/',
//         permanent: false,
//       },
//     }
//   }

//   return session
// }