import Head from 'next/head';
import React from 'react';
import styles from '../styles/Home.module.css'
import {signIn} from 'next-auth/react'
import { SessionProvider } from "next-auth/react";
import { getCsrfToken } from "next-auth/react"

const Login = ({ csrfToken }) => {

  // console.log(providers);

  return (

    <div className={"ggg"}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-full items-center justify-center bg-red-300">
      <form method="post" action="/api/auth/callback/credentials">
        <input name="csrfToken" type="hidden" defaultValue={csrfToken} />
        <label>
          Username
          <input name="username" type="text" />
        </label>
        <label>
          Password
          <input name="password" type="password" />
        </label>
        <button type="submit">Sign in</button>
      </form>
      </main>
    </div>
  )
};

export default Login;

// This is the recommended way for Next.js 9.3 or newer
export async function getServerSideProps(context) {
  return {
    props: {
      csrfToken: await getCsrfToken(context),
    },
  }
}

