import Head from 'next/head';
import React from 'react';
import styles from '../styles/Home.module.css'
import {signIn} from 'next-auth/react'
import { SessionProvider } from "next-auth/react";
import { getCsrfToken } from "next-auth/react"

const Login = ({ csrfToken }) => {

  // console.log(providers);

  return (

    <div className={"ggg"}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-full items-center justify-center bg-red-300">
      <div className="w-screen h-screen flex items-center justify-center bg-red-300">
              <div className="flex flex-col">
              <form className="flex flex-col" method="post" action="/api/auth/callback/credentials">
                    <input name="csrfToken" type="hidden" defaultValue={csrfToken} />
                    <label className="p-5 ">
                    Username
                    <input className="ml-3" name="email" type="text" />
                    </label>
                    <label className="p-5">
                    Password
                    <input className='ml-3' name="password" type="password" />
                    </label>
                    <button className="bg-gray-500 rounded-xl" type="submit">Sign in</button>
                </form>
              </div>
          </div>
      </main>
    </div>
  )
};

export default Login;

// This is the recommended way for Next.js 9.3 or newer
export async function getServerSideProps(context) {
  return {
    props: {
      csrfToken: await getCsrfToken(context),
    },
  }
}

